# from
# https://www.linode.com/docs/guides/install-graphite-and-grafana/#docker-compose-configuration-for-graphite-and-grafana
#
# You will need to create these 2 volumes 
# $ docker volume create --name=grafana-volume
# $ docker volume create --name=graphite-volume
#
# Then you can start everything
# $ docker-compose up -d
# And you should see 2 machines running
# $ docker ps
#
# Allow the Grafana http port
# $ sudo ufw allow proto tcp from any to any port 3000
#
# Allow the Python pickle port for Graphite
# $ sudo ufw allow proto tcp from any to any port 2004
#
version: "3"
services:
  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: always
    ports:
      - 3000:3000
    networks:
      - grafana-net
    volumes:
      - grafana-volume:/var/lib/grafana

  graphite:
    image: graphiteapp/graphite-statsd
    container_name: graphite
    restart: always
    ports:
      - "2003-2004:2003-2004"
    networks:
      - grafana-net
    volumes:
      - graphite-volume:/opt/graphite/storage
    
networks:
  grafana-net:

volumes:
  grafana-volume:
    external: true
  graphite-volume:
    external: true
