# from
# https://www.linode.com/docs/guides/install-graphite-and-grafana/#docker-compose-configuration-for-graphite-and-grafana
version: "3"
services:
  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: always
    ports:
      - 3000:3000
    networks:
      - grafana-net
    volumes:
      - grafana-volume:/var/lib/grafana

  graphite:
    image: graphiteapp/graphite-statsd
    container_name: graphite
    restart: always
    ports:
      - "2003-2004:2003-2004"
    networks:
      - grafana-net
    volumes:
      - graphite-volume:/opt/graphite/storage
    
networks:
  grafana-net:

volumes:
  grafana-volume:
    external: true
  graphite-volume:
    external: true
